/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { FlexProps, IconProps, ImageProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type IPhone13141OverridesProps = {
    IPhone13141?: PrimitiveOverrideProps<ViewProps>;
    "hopper lines"?: PrimitiveOverrideProps<ViewProps>;
    "Line 12"?: PrimitiveOverrideProps<IconProps>;
    "Line 13153101"?: PrimitiveOverrideProps<IconProps>;
    "Line 14153102"?: PrimitiveOverrideProps<IconProps>;
    "Line 15153103"?: PrimitiveOverrideProps<IconProps>;
    "Line 16183224"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 8153483"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 9"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 10"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 11"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 12"?: PrimitiveOverrideProps<IconProps>;
    "Line 17183228"?: PrimitiveOverrideProps<IconProps>;
    "Line 18183234"?: PrimitiveOverrideProps<IconProps>;
    "Chemical lines"?: PrimitiveOverrideProps<ViewProps>;
    "Line 2"?: PrimitiveOverrideProps<IconProps>;
    "Line 3"?: PrimitiveOverrideProps<IconProps>;
    "Line 4"?: PrimitiveOverrideProps<IconProps>;
    "Line 5"?: PrimitiveOverrideProps<IconProps>;
    "Line 6"?: PrimitiveOverrideProps<IconProps>;
    "Line 7"?: PrimitiveOverrideProps<IconProps>;
    "Line 8"?: PrimitiveOverrideProps<IconProps>;
    "Chemical arrows"?: PrimitiveOverrideProps<ViewProps>;
    "Arrow 1"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 2"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 3"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 5"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 8153495"?: PrimitiveOverrideProps<IconProps>;
    "WhatsApp_Image_2024-08-22_at_9.05.23_AM-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "Blinding lights"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 10"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 11"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 12"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 13"?: PrimitiveOverrideProps<IconProps>;
    "Rectangle 1"?: PrimitiveOverrideProps<ViewProps>;
    "smart Logo"?: PrimitiveOverrideProps<ViewProps>;
    "Home Icons"?: PrimitiveOverrideProps<FlexProps>;
    Home?: PrimitiveOverrideProps<ViewProps>;
    alarm?: PrimitiveOverrideProps<ViewProps>;
    "WhatsApp_Image_2024-08-20_at_1.11.29_AM-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.12.34_AM-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.12.43_AM-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.10.58_AM-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "Mixer truck"?: PrimitiveOverrideProps<ImageProps>;
    Mixer?: PrimitiveOverrideProps<FlexProps>;
    "WhatsApp_Image_2024-08-22_at_9.25.21_PM__1_-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.21.57_AM-removebg-preview 1"?: PrimitiveOverrideProps<ImageProps>;
    Buttons15115?: PrimitiveOverrideProps<FlexProps>;
    "power on button151237"?: PrimitiveOverrideProps<IconProps>;
    "Stop button151249"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 4"?: PrimitiveOverrideProps<IconProps>;
    "Group 5"?: PrimitiveOverrideProps<ViewProps>;
    "Line 18183230"?: PrimitiveOverrideProps<IconProps>;
    "WhatsApp_Image_2024-08-20_at_1.18.32_AM-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 3"?: PrimitiveOverrideProps<FlexProps>;
    Buttons151357?: PrimitiveOverrideProps<FlexProps>;
    "power on button151304"?: PrimitiveOverrideProps<IconProps>;
    "Stop button151354"?: PrimitiveOverrideProps<IconProps>;
    "rotate-right151421"?: PrimitiveOverrideProps<ViewProps>;
    "rotate-right151429"?: PrimitiveOverrideProps<ViewProps>;
    "Ellipse 3"?: PrimitiveOverrideProps<IconProps>;
    "WhatsApp_Image_2024-08-20_at_1.18.36_AM-removebg-preview 3132413"?: PrimitiveOverrideProps<ImageProps>;
    "Red button151352"?: PrimitiveOverrideProps<IconProps>;
    Buttons153526?: PrimitiveOverrideProps<FlexProps>;
    "arrow-up-square-2151379"?: PrimitiveOverrideProps<ViewProps>;
    "Stop button151386"?: PrimitiveOverrideProps<IconProps>;
    "Frame 1151437"?: PrimitiveOverrideProps<FlexProps>;
    "WhatsApp Image 2024-08-22 at 9.06.53 AM 3132309"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.02.31_AM-removebg-preview 4"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.02.31_AM-removebg-preview 5"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.02.31_AM-removebg-preview 6"?: PrimitiveOverrideProps<ImageProps>;
    "Ellipse 9"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 8"?: PrimitiveOverrideProps<IconProps>;
    "Ellipse 7"?: PrimitiveOverrideProps<IconProps>;
    "Stop button151416"?: PrimitiveOverrideProps<IconProps>;
    "Stop button151414"?: PrimitiveOverrideProps<IconProps>;
    "Stop button151418"?: PrimitiveOverrideProps<IconProps>;
    "arrow-up-square-2151393"?: PrimitiveOverrideProps<ViewProps>;
    "arrow-up-square-2151400"?: PrimitiveOverrideProps<ViewProps>;
    "arrow-up-square-2151407"?: PrimitiveOverrideProps<ViewProps>;
    "Water Containers"?: PrimitiveOverrideProps<FlexProps>;
    "Water container 1"?: PrimitiveOverrideProps<FlexProps>;
    "WhatsApp_Image_2024-08-20_at_1.18.51_AM-removebg-preview 4"?: PrimitiveOverrideProps<ImageProps>;
    "power on button151223"?: PrimitiveOverrideProps<IconProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.07_AM-removebg-preview 11"?: PrimitiveOverrideProps<ImageProps>;
    "Red button151347"?: PrimitiveOverrideProps<IconProps>;
    "Water container 2"?: PrimitiveOverrideProps<FlexProps>;
    "WhatsApp_Image_2024-08-20_at_1.18.51_AM-removebg-preview 3"?: PrimitiveOverrideProps<ImageProps>;
    "power of button151224"?: PrimitiveOverrideProps<IconProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.07_AM-removebg-preview 7132399"?: PrimitiveOverrideProps<ImageProps>;
    "Red button151349"?: PrimitiveOverrideProps<IconProps>;
    Chemicals?: PrimitiveOverrideProps<FlexProps>;
    "Chemical 1"?: PrimitiveOverrideProps<FlexProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.31_AM-removebg-preview 10"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.47_AM-removebg-preview 5"?: PrimitiveOverrideProps<ImageProps>;
    "Red button151337"?: PrimitiveOverrideProps<IconProps>;
    Buttons151174?: PrimitiveOverrideProps<FlexProps>;
    "arrow-up-square-2151459"?: PrimitiveOverrideProps<ViewProps>;
    "Stop button151245"?: PrimitiveOverrideProps<IconProps>;
    "Chemical 2"?: PrimitiveOverrideProps<FlexProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.31_AM-removebg-preview 9"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.47_AM-removebg-preview 6"?: PrimitiveOverrideProps<ImageProps>;
    "Red button151335"?: PrimitiveOverrideProps<IconProps>;
    Buttons151182?: PrimitiveOverrideProps<FlexProps>;
    "arrow-up-square-2151466"?: PrimitiveOverrideProps<ViewProps>;
    "Stop button151243"?: PrimitiveOverrideProps<IconProps>;
    "Chemical 3"?: PrimitiveOverrideProps<FlexProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.31_AM-removebg-preview 11"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.47_AM-removebg-preview 4"?: PrimitiveOverrideProps<ImageProps>;
    "Red button151339"?: PrimitiveOverrideProps<IconProps>;
    Buttons151173?: PrimitiveOverrideProps<FlexProps>;
    "arrow-up-square-2151452"?: PrimitiveOverrideProps<ViewProps>;
    "Stop button151247"?: PrimitiveOverrideProps<IconProps>;
    Hopper?: PrimitiveOverrideProps<FlexProps>;
    "WhatsApp_Image_2024-08-20_at_1.23.02_AM__1_-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.18.36_AM-removebg-preview 3132383"?: PrimitiveOverrideProps<ImageProps>;
    "Group 10"?: PrimitiveOverrideProps<ViewProps>;
    "Group 2"?: PrimitiveOverrideProps<ViewProps>;
    "WhatsApp_Image_2024-08-22_at_9.26.52_PM-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.07_AM-removebg-preview 7132329"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.07_AM-removebg-preview 8"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.07_AM-removebg-preview 9"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.19.07_AM-removebg-preview 10"?: PrimitiveOverrideProps<ImageProps>;
    "Red button151364"?: PrimitiveOverrideProps<IconProps>;
    "Red button151362"?: PrimitiveOverrideProps<IconProps>;
    "Red button151360"?: PrimitiveOverrideProps<IconProps>;
    "Red button151358"?: PrimitiveOverrideProps<IconProps>;
    "Group 1"?: PrimitiveOverrideProps<ViewProps>;
    "WhatsApp_Image_2024-08-22_at_9.25.21_PM-removebg-preview 5"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.25.21_PM-removebg-preview 6"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.25.21_PM-removebg-preview 7"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.25.21_PM-removebg-preview 8"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-20_at_1.28.26_AM__1_-removebg-preview 2"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.11.51_AM-removebg-preview 6"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.11.51_AM-removebg-preview 7"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.11.51_AM-removebg-preview 8"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.11.51_AM-removebg-preview 9"?: PrimitiveOverrideProps<ImageProps>;
    "Frame 2"?: PrimitiveOverrideProps<FlexProps>;
    "arrow-up-square-2151518"?: PrimitiveOverrideProps<ViewProps>;
    "Stop button151251"?: PrimitiveOverrideProps<IconProps>;
    "Frame 1151438"?: PrimitiveOverrideProps<FlexProps>;
    "WhatsApp Image 2024-08-22 at 9.06.53 AM 3151439"?: PrimitiveOverrideProps<ImageProps>;
    "Water lines"?: PrimitiveOverrideProps<ViewProps>;
    "Line 9"?: PrimitiveOverrideProps<IconProps>;
    "Line 10"?: PrimitiveOverrideProps<IconProps>;
    "Line 11"?: PrimitiveOverrideProps<IconProps>;
    "Water arrows"?: PrimitiveOverrideProps<ViewProps>;
    "Arrow 4"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 6"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 7"?: PrimitiveOverrideProps<IconProps>;
    "Arrow 8153527"?: PrimitiveOverrideProps<IconProps>;
    Buttons15197?: PrimitiveOverrideProps<FlexProps>;
    "power of button151232"?: PrimitiveOverrideProps<IconProps>;
    Vector151230?: PrimitiveOverrideProps<IconProps>;
    Vector151228?: PrimitiveOverrideProps<IconProps>;
    Vector151226?: PrimitiveOverrideProps<IconProps>;
    "Conveyor line"?: PrimitiveOverrideProps<ImageProps>;
    "Line 14183210"?: PrimitiveOverrideProps<IconProps>;
    "Line 15183212"?: PrimitiveOverrideProps<IconProps>;
    "Line 16183220"?: PrimitiveOverrideProps<IconProps>;
    "WhatsApp_Image_2024-08-22_at_9.05.23_AM-removebg-preview 3"?: PrimitiveOverrideProps<ImageProps>;
    "WhatsApp_Image_2024-08-22_at_9.05.23_AM-removebg-preview 4"?: PrimitiveOverrideProps<ImageProps>;
    "Line 13183218"?: PrimitiveOverrideProps<IconProps>;
    "Line 19"?: PrimitiveOverrideProps<IconProps>;
    "Line 17183222"?: PrimitiveOverrideProps<IconProps>;
    "Line 18183226"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type IPhone13141Props = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: IPhone13141OverridesProps | undefined | null;
}>;
export default function IPhone13141(props: IPhone13141Props): React.ReactElement;
